spring:
  application:
    name: zuul
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: true
zuul:
  routes:
    admin: /admin/**