server:
  port: 8001
spring:
  application:
    name: admin
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/zacharychao?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
