server:
  port: 8060
mybatis:
  type-aliases-package: com.zacharychao.mvc.user.entity
  mapper-locations:
  - classpath:mappers/*.xml
spring:
  datasource:
    url: jdbc:mysql://47.98.163.175:3306/zacharychao?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zacharychao